targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "wasm32-unknown-unknown" },
]

[licenses]
unlicensed = "deny"
allow-osi-fsf-free = "both"
copyleft = "allow"
confidence-threshold = 0.93
allow = ["Apache-2.0", "Apache-2.0 WITH LLVM-exception", "MIT", "MPL-2.0", "GPL-3.0", "BSD-2-Clause", "OpenSSL"]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]
