##################################### Haskell ####################################

[tasks.hs-demo]
script = '''
    cargo build

    cd bindings/haskell
    # link Rust libs we just built
    # required because cabal does not support relative paths outside its root dir :/
    ln -Fs ../../../target .

    # run the simple Haskell demo
    cabal run
'''
